Added rule to enforce object property shorthand where possible
coffeelint/coffeelint pull request #90
Opened 2020-09-21 21:04 UTC by MrMcGoats

2020-09-22 02:25 UTC, UziTech requested changes
remove vim comments

2020-09-22 03:55 UTC, UziTech approved these changes

2020-09-22 17:59 UTC, jacksonrayhamilton commented
Thanks @MrMcGoats for your contribution and @UziTech for being willing to involve me in reviewing it.

@UziTech I am mostly only invested in maintaining the CoffeeLint V1 branch,  so feel free to assign me to any PRs to that, but I am not too interested in other changes.

2020-09-23 07:29 UTC, sibiraj-s approved these changes
LGTM 👍

2020-09-23 13:14 UTC, merged